/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.io.File;
import java.io.IOException;
import javax.swing.table.DefaultTableModel;
import storm.Cidade;
import storm.Xml;
import java.util.List;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import javax.xml.parsers.ParserConfigurationException;
import org.w3c.dom.Document;
import org.xml.sax.SAXException;

/**
 *
 * @author matheus
 */
public class Previsao extends javax.swing.JFrame {

    /**
     * Creates new form Previsoes
     */
    Cidade cidade = new Cidade();

    public Previsao() {
        initComponents();
        carregaEstados();

    }
    
    private void deleta(){
        String nome = "out.xml";  
        File f = new File(nome);  
        f.delete();
    }

    private void carregaEstados() {
        //jComboEstado.removeAllItems();
        String mostra;
        Cidade city = new Cidade();
        city.lerEstadoCidade("estados.txt");
        Vector vEstados = new Vector();

        for (int a = 0; a < city.nomeCidades.size(); a++) {
            mostra = city.nomeCidades.get(a);
            //jComboEstado.addItem(mostra);
            vEstados.add(mostra);
        }

        jComboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(vEstados));
        //jComboEstado.setSelectedIndex(-1); //Deixa o comboBox em branco
    }

    private Vector carregaCidades(String cidade) {
        String c = cidade + ".txt";
        Vector vCidades = new Vector();
        //jComboCidade.removeAllItems();
        String mostra;
        Cidade city = new Cidade();
        city.lerEstadoCidade(c);

        for (int a = 0; a < city.nomeCidades.size(); a++) {
            mostra = city.nomeCidades.get(a);
            vCidades.add(mostra);

            a++;
            //jComboCidade.addItem(mostra);
        }

        return vCidades;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        abas = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboEstado = new javax.swing.JComboBox<>();
        jComboCidade = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelCidade = new javax.swing.JLabel();
        jLabelEstado = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabelData1 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jLabelData2 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jLabelData3 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jLabelData5 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jLabelData4 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabelData6 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTablePrevisao1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTablePrevisao5 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTablePrevisao2 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTablePrevisao6 = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTablePrevisao4 = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTablePrevisao7 = new javax.swing.JTable();
        jLabelHora5 = new javax.swing.JLabel();
        jLabelHora1 = new javax.swing.JLabel();
        jLabelHora2 = new javax.swing.JLabel();
        jLabelHora3 = new javax.swing.JLabel();
        jLabelHora7 = new javax.swing.JLabel();
        jLabelHora6 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTablePrevisao3 = new javax.swing.JTable();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTablePrevisao8 = new javax.swing.JTable();
        jLabelHora8 = new javax.swing.JLabel();
        jLabelHora4 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jLabelCidade1 = new javax.swing.JLabel();
        jLabelEstado1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        abas.setToolTipText("");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboEstado.setToolTipText("Seleicone");
        jComboEstado.setName(""); // NOI18N
        jComboEstado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboEstadoItemStateChanged(evt);
            }
        });
        jComboEstado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboEstadoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboEstadoMouseEntered(evt);
            }
        });
        jComboEstado.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jComboEstadoComponentHidden(evt);
            }
        });
        jComboEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboEstadoActionPerformed(evt);
            }
        });

        jComboCidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboCidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboCidadeMouseEntered(evt);
            }
        });
        jComboCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboCidadeActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cidade");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Estado (UF)");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jComboEstado, 0, 190, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 485, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboCidade, 0, 190, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(5, 5, 5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 439, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        abas.addTab("Escolha a cidade", jPanel4);

        jPanel5.setPreferredSize(new java.awt.Dimension(631, 600));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Localização"));

        jLabelCidade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCidade.setText("Cidade");

        jLabelEstado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEstado.setText("Estado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCidade)
                    .addComponent(jLabelEstado))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações"));

        jButton3.setText("Ver");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabelData1.setText("Data 1");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelData1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelData1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jButton6.setText("Ver");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabelData2.setText("Data 2");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelData2, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelData2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jButton7.setText("Ver");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabelData3.setText("Data 3");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelData3, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelData3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jButton8.setText("Ver");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabelData5.setText("Data 5");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelData5, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelData5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jButton9.setText("Ver");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabelData4.setText("Data 4");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelData4, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelData4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jLabelData6.setText("Data 6");

        jButton10.setText("Ver");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelData6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelData6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10))
                .addContainerGap())
        );

        jButton12.setText("Voltar");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(360, 360, 360)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(382, 382, 382)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addComponent(jButton12)
                .addGap(156, 156, 156))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 443, Short.MAX_VALUE)
                .addContainerGap())
        );

        abas.addTab("Previsões", jPanel5);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações"));

        jTablePrevisao1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "Previsão"
            }
        ));
        jScrollPane3.setViewportView(jTablePrevisao1);

        jTablePrevisao5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "Previsão"
            }
        ));
        jScrollPane4.setViewportView(jTablePrevisao5);

        jTablePrevisao2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "Previsão"
            }
        ));
        jScrollPane5.setViewportView(jTablePrevisao2);

        jTablePrevisao6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "Previsão"
            }
        ));
        jScrollPane6.setViewportView(jTablePrevisao6);

        jTablePrevisao4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "Previsão"
            }
        ));
        jScrollPane7.setViewportView(jTablePrevisao4);

        jTablePrevisao7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "Previsão"
            }
        ));
        jScrollPane8.setViewportView(jTablePrevisao7);

        jLabelHora5.setText("Hora 5");

        jLabelHora1.setText("Hora 1");

        jLabelHora2.setText("Hora 2");

        jLabelHora3.setText("Hora 3");

        jLabelHora7.setText("Hora 7");

        jLabelHora6.setText("Hora 6");

        jTablePrevisao3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "Previsão"
            }
        ));
        jScrollPane9.setViewportView(jTablePrevisao3);

        jTablePrevisao8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome", "Previsão"
            }
        ));
        jScrollPane10.setViewportView(jTablePrevisao8);

        jLabelHora8.setText("Hora 8");

        jLabelHora4.setText("Hora 4");

        jButton13.setText("Voltar");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelHora1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelHora2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelHora3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelHora4)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelHora5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabelHora6)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelHora7)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelHora8)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(388, 388, 388)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHora2)
                    .addComponent(jLabelHora3)
                    .addComponent(jLabelHora1)
                    .addComponent(jLabelHora4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabelHora5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelHora6)
                                    .addComponent(jLabelHora7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabelHora8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jButton13))
        );

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder("Localização"));

        jLabelCidade1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCidade1.setText("Cidade");

        jLabelEstado1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEstado1.setText("Estado");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCidade1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelEstado1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCidade1)
                    .addComponent(jLabelEstado1))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        abas.addTab("Previsão detalhada", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(abas)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(abas, javax.swing.GroupLayout.PREFERRED_SIZE, 586, Short.MAX_VALUE)
        );

        abas.getAccessibleContext().setAccessibleName("Escolha a cidade");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here

        Login login = new Login();

        login.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboCidadeActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboCidadeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//jComboCidade.getSelectedIndex();

        String cselect = jComboEstado.getSelectedItem().toString();
        String mostra;
        String c = cselect + ".txt";


        int index = jComboCidade.getSelectedIndex();
        deleta();
        index = (index * 2) + 1;
        Cidade city = new Cidade();
        city.lerEstadoCidade(c);

        mostra = city.nomeCidades.get(index);

        Xml xml = new Xml();
        Previsao prev = new Previsao();
         Document doc = null;
        try {
            doc=   xml.BaixaArquivo(mostra);
        } catch (IOException ex) {
            Logger.getLogger(Previsao.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SAXException ex) {
            Logger.getLogger(Previsao.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParserConfigurationException ex) {
            Logger.getLogger(Previsao.class.getName()).log(Level.SEVERE, null, ex);
        }



        

       
 
        cidade = xml.getXmlCidade(doc);

        xml.XmlPrevisao(doc, cidade);

       
        cidade.LeArray();
        jLabelCidade.setText(jComboCidade.getSelectedItem().toString());
        jLabelCidade1.setText(jComboCidade.getSelectedItem().toString());
        jLabelEstado.setText(jComboEstado.getSelectedItem().toString());
        jLabelEstado1.setText(jComboEstado.getSelectedItem().toString());

        javax.swing.JLabel labelHora[] = {jLabelData1, jLabelData2, jLabelData3, jLabelData4, jLabelData5, jLabelData6};

        for (int i = 0; i < 6; i++) {
            String diaHora[] = new String[2];
            diaHora = cidade.prev.get(i * 8).getDia().split(" ");
            labelHora[i].setText(diaHora[0]);
        }


        abas.setSelectedIndex(1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        javax.swing.JTable arrayTabelas[] = {jTablePrevisao1, jTablePrevisao2, jTablePrevisao3, jTablePrevisao4, jTablePrevisao5, jTablePrevisao6, jTablePrevisao7, jTablePrevisao8};
        Vector<DefaultTableModel> tabela = new Vector<>();
        for (int i = 0; i < 8; i++) {
            DefaultTableModel temp = (DefaultTableModel) arrayTabelas[i].getModel();
            temp.setNumRows(0);
            tabela.add(temp);
        }
        int aux=0;
        for (int i = 0; i < 8; i++) {
            String[] linha1 = new String[]{"Agitação", cidade.prev.get(i).getAgitacao()};
            String[] linha2 = new String[]{"Altura", cidade.prev.get(i).getAltura()};
            String[] linha3 = new String[]{"Direção", cidade.prev.get(i).getDirecao()};
            String[] linha4 = new String[]{"Vento", cidade.prev.get(i).getVento()};
            String[] linha5 = new String[]{"Vento Dir", cidade.prev.get(i).getVentoDir()};
            tabela.get(aux).addRow(linha1);
            tabela.get(aux).addRow(linha2);
            tabela.get(aux).addRow(linha3);
            tabela.get(aux).addRow(linha4);
            tabela.get(aux).addRow(linha5);
            aux++;
        }

        javax.swing.JLabel labelHora[] = {jLabelHora1, jLabelHora2, jLabelHora3, jLabelHora4, jLabelHora5, jLabelHora6, jLabelHora7, jLabelHora8};

        int aux2=0;
        for (int i = 0; i < 8; i++) {
            String diaHora[] = new String[2];
            diaHora = cidade.prev.get(i).getDia().split(" ");
            labelHora[aux2].setText(diaHora[1]);
            labelHora[aux2].setText(diaHora[1]);
            labelHora[aux2].setText(diaHora[1]);
            labelHora[aux2].setText(diaHora[1]);
            labelHora[aux2].setText(diaHora[1]);
            labelHora[aux2].setText(diaHora[1]);
            labelHora[aux2].setText(diaHora[1]);
            labelHora[aux2].setText(diaHora[1]);
            aux2++;
        }

        abas.setSelectedIndex(2);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        javax.swing.JTable arrayTabelas[] = {jTablePrevisao1, jTablePrevisao2, jTablePrevisao3, jTablePrevisao4, jTablePrevisao5, jTablePrevisao6, jTablePrevisao7, jTablePrevisao8};
        Vector<DefaultTableModel> tabela = new Vector<>();
        for (int i = 0; i < 8; i++) {
            DefaultTableModel temp = (DefaultTableModel) arrayTabelas[i].getModel();
            temp.setNumRows(0);
            tabela.add(temp);
        }

        int aux=0;
        for (int i = 8; i < 16; i++) {
            String[] linha1 = new String[]{"Agitação", cidade.prev.get(i).getAgitacao()};
            String[] linha2 = new String[]{"Altura", cidade.prev.get(i).getAltura()};
            String[] linha3 = new String[]{"Direção", cidade.prev.get(i).getDirecao()};
            String[] linha4 = new String[]{"Vento", cidade.prev.get(i).getVento()};
            String[] linha5 = new String[]{"Vento Dir", cidade.prev.get(i).getVentoDir()};
            tabela.get(aux).addRow(linha1);
            tabela.get(aux).addRow(linha2);
            tabela.get(aux).addRow(linha3);
            tabela.get(aux).addRow(linha4);
            tabela.get(aux).addRow(linha5);
            aux++;
        }
  
        javax.swing.JLabel labelHora[] = {jLabelHora1, jLabelHora2, jLabelHora3, jLabelHora4, jLabelHora5, jLabelHora6, jLabelHora7, jLabelHora8};

        int aux2=0;
        for (int i = 8; i < 16; i++) {
            String diaHora[] = new String[2];
            diaHora = cidade.prev.get(i).getDia().split(" ");
            labelHora[aux2].setText(diaHora[1]);
            labelHora[aux2].setText(diaHora[1]);
            labelHora[aux2].setText(diaHora[1]);
            labelHora[aux2].setText(diaHora[1]);
            labelHora[aux2].setText(diaHora[1]);
            labelHora[aux2].setText(diaHora[1]);
            labelHora[aux2].setText(diaHora[1]);
            labelHora[aux2].setText(diaHora[1]);
            aux2++;
        }

        abas.setSelectedIndex(2);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        javax.swing.JTable arrayTabelas[] = {jTablePrevisao1, jTablePrevisao2, jTablePrevisao3, jTablePrevisao4, jTablePrevisao5, jTablePrevisao6, jTablePrevisao7, jTablePrevisao8};
        Vector<DefaultTableModel> tabela = new Vector<>();
        for (int i = 0; i < 8; i++) {
            DefaultTableModel temp = (DefaultTableModel) arrayTabelas[i].getModel();
            temp.setNumRows(0);
            tabela.add(temp);
        }

        int aux=0;
        for (int i = 16; i < 24; i++) {
            String[] linha1 = new String[]{"Agitação", cidade.prev.get(i).getAgitacao()};
            String[] linha2 = new String[]{"Altura", cidade.prev.get(i).getAltura()};
            String[] linha3 = new String[]{"Direção", cidade.prev.get(i).getDirecao()};
            String[] linha4 = new String[]{"Vento", cidade.prev.get(i).getVento()};
            String[] linha5 = new String[]{"Vento Dir", cidade.prev.get(i).getVentoDir()};
            tabela.get(aux).addRow(linha1);
            tabela.get(aux).addRow(linha2);
            tabela.get(aux).addRow(linha3);
            tabela.get(aux).addRow(linha4);
            tabela.get(aux).addRow(linha5);
            aux++;
        }
  
        javax.swing.JLabel labelHora[] = {jLabelHora1, jLabelHora2, jLabelHora3, jLabelHora4, jLabelHora5, jLabelHora6, jLabelHora7, jLabelHora8};

        int aux2=0;
        for (int i = 16; i < 24; i++) {
            String diaHora[] = new String[2];
            diaHora = cidade.prev.get(i).getDia().split(" ");
            labelHora[aux2].setText(diaHora[1]);
            labelHora[aux2].setText(diaHora[1]);
            labelHora[aux2].setText(diaHora[1]);
            labelHora[aux2].setText(diaHora[1]);
            labelHora[aux2].setText(diaHora[1]);
            labelHora[aux2].setText(diaHora[1]);
            labelHora[aux2].setText(diaHora[1]);
            labelHora[aux2].setText(diaHora[1]);
            aux2++;
        }

        abas.setSelectedIndex(2);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

        javax.swing.JTable arrayTabelas[] = {jTablePrevisao1, jTablePrevisao2, jTablePrevisao3, jTablePrevisao4, jTablePrevisao5, jTablePrevisao6, jTablePrevisao7, jTablePrevisao8};
        Vector<DefaultTableModel> tabela = new Vector<>();
        for (int i = 0; i < 8; i++) {
            DefaultTableModel temp = (DefaultTableModel) arrayTabelas[i].getModel();
            temp.setNumRows(0);
            tabela.add(temp);
        }

         int aux=0;
        for (int i = 32; i < 40; i++) {
            String[] linha1 = new String[]{"Agitação", cidade.prev.get(i).getAgitacao()};
            String[] linha2 = new String[]{"Altura", cidade.prev.get(i).getAltura()};
            String[] linha3 = new String[]{"Direção", cidade.prev.get(i).getDirecao()};
            String[] linha4 = new String[]{"Vento", cidade.prev.get(i).getVento()};
            String[] linha5 = new String[]{"Vento Dir", cidade.prev.get(i).getVentoDir()};
            tabela.get(aux).addRow(linha1);
            tabela.get(aux).addRow(linha2);
            tabela.get(aux).addRow(linha3);
            tabela.get(aux).addRow(linha4);
            tabela.get(aux).addRow(linha5);
            aux++;
        }

        javax.swing.JLabel labelHora[] = {jLabelHora1, jLabelHora2, jLabelHora3, jLabelHora4, jLabelHora5, jLabelHora6, jLabelHora7, jLabelHora8};

        int aux2=0;
        for (int i = 32; i < 40; i++) {
            String diaHora[] = new String[2];
            diaHora = cidade.prev.get(i).getDia().split(" ");
            labelHora[aux2].setText(diaHora[1]);
            labelHora[aux2].setText(diaHora[1]);
            labelHora[aux2].setText(diaHora[1]);
            labelHora[aux2].setText(diaHora[1]);
            labelHora[aux2].setText(diaHora[1]);
            labelHora[aux2].setText(diaHora[1]);
            labelHora[aux2].setText(diaHora[1]);
            labelHora[aux2].setText(diaHora[1]);
            aux2++;
        }

        abas.setSelectedIndex(2);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        javax.swing.JTable arrayTabelas[] = {jTablePrevisao1, jTablePrevisao2, jTablePrevisao3, jTablePrevisao4, jTablePrevisao5, jTablePrevisao6, jTablePrevisao7, jTablePrevisao8};
        Vector<DefaultTableModel> tabela = new Vector<>();
        for (int i = 0; i < 8; i++) {
            DefaultTableModel temp = (DefaultTableModel) arrayTabelas[i].getModel();
            temp.setNumRows(0);
            tabela.add(temp);
        }

        int aux=0;
        for (int i = 24; i < 32; i++) {
            String[] linha1 = new String[]{"Agitação", cidade.prev.get(i).getAgitacao()};
            String[] linha2 = new String[]{"Altura", cidade.prev.get(i).getAltura()};
            String[] linha3 = new String[]{"Direção", cidade.prev.get(i).getDirecao()};
            String[] linha4 = new String[]{"Vento", cidade.prev.get(i).getVento()};
            String[] linha5 = new String[]{"Vento Dir", cidade.prev.get(i).getVentoDir()};
            tabela.get(aux).addRow(linha1);
            tabela.get(aux).addRow(linha2);
            tabela.get(aux).addRow(linha3);
            tabela.get(aux).addRow(linha4);
            tabela.get(aux).addRow(linha5);
            aux++;
        }

        javax.swing.JLabel labelHora[] = {jLabelHora1, jLabelHora2, jLabelHora3, jLabelHora4, jLabelHora5, jLabelHora6, jLabelHora7, jLabelHora8};

        int aux2=0;
        for (int i = 24; i < 32; i++) {
            String diaHora[] = new String[2];
            diaHora = cidade.prev.get(i).getDia().split(" ");
            labelHora[aux2].setText(diaHora[1]);
            labelHora[aux2].setText(diaHora[1]);
            labelHora[aux2].setText(diaHora[1]);
            labelHora[aux2].setText(diaHora[1]);
            labelHora[aux2].setText(diaHora[1]);
            labelHora[aux2].setText(diaHora[1]);
            labelHora[aux2].setText(diaHora[1]);
            labelHora[aux2].setText(diaHora[1]);
            aux2++;
        }

        abas.setSelectedIndex(2);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

        javax.swing.JTable arrayTabelas[] = {jTablePrevisao1, jTablePrevisao2, jTablePrevisao3, jTablePrevisao4, jTablePrevisao5, jTablePrevisao6, jTablePrevisao7, jTablePrevisao8};
        Vector<DefaultTableModel> tabela = new Vector<>();
        for (int i = 0; i < 8; i++) {
            DefaultTableModel temp = (DefaultTableModel) arrayTabelas[i].getModel();
            temp.setNumRows(0);
            tabela.add(temp);
        }

        int aux=0;
        int cont=0;
        cont = 40 + ((cidade.prev.size())%8);
        for (int i = 40; i < cont; i++) {
            String[] linha1 = new String[]{"Agitação", cidade.prev.get(i).getAgitacao()};
            String[] linha2 = new String[]{"Altura", cidade.prev.get(i).getAltura()};
            String[] linha3 = new String[]{"Direção", cidade.prev.get(i).getDirecao()};
            String[] linha4 = new String[]{"Vento", cidade.prev.get(i).getVento()};
            String[] linha5 = new String[]{"Vento Dir", cidade.prev.get(i).getVentoDir()};
            tabela.get(aux).addRow(linha1);
            tabela.get(aux).addRow(linha2);
            tabela.get(aux).addRow(linha3);
            tabela.get(aux).addRow(linha4);
            tabela.get(aux).addRow(linha5);
            aux++;
        }

        javax.swing.JLabel labelHora[] = {jLabelHora1, jLabelHora2, jLabelHora3, jLabelHora4, jLabelHora5, jLabelHora6, jLabelHora7, jLabelHora8};

        int aux2=0;
        for (int i = 40; i < cont; i++) {
            String diaHora[] = new String[2];
            diaHora = cidade.prev.get(i).getDia().split(" ");
            labelHora[aux2].setText(diaHora[1]);
            labelHora[aux2].setText(diaHora[1]);
            labelHora[aux2].setText(diaHora[1]);
            labelHora[aux2].setText(diaHora[1]);
            labelHora[aux2].setText(diaHora[1]);
            labelHora[aux2].setText(diaHora[1]);
            labelHora[aux2].setText(diaHora[1]);
            labelHora[aux2].setText(diaHora[1]);
            aux2++;
        }

        abas.setSelectedIndex(2);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jComboEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboEstadoActionPerformed
        // TODO add your handling code here:
        Vector cidades = carregaCidades(jComboEstado.getSelectedItem().toString());
        jComboCidade.setModel(new javax.swing.DefaultComboBoxModel<>(cidades));
    }//GEN-LAST:event_jComboEstadoActionPerformed

    private void jComboEstadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboEstadoMouseClicked
        // TODO add your handling code here:
        //carregaCidades(jComboEstado.getSelectedItem().toString());
    }//GEN-LAST:event_jComboEstadoMouseClicked

    private void jComboEstadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboEstadoMouseEntered
    
    }//GEN-LAST:event_jComboEstadoMouseEntered

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        abas.setSelectedIndex(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        abas.setSelectedIndex(1);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jComboEstadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboEstadoItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboEstadoItemStateChanged

    private void jComboCidadeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboCidadeMouseEntered
        // TODO add your handling code here:
        //carregaCidades(jComboEstado.getSelectedItem().toString());

    }//GEN-LAST:event_jComboCidadeMouseEntered

    private void jComboEstadoComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jComboEstadoComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboEstadoComponentHidden

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Previsao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Previsao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Previsao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Previsao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Previsao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane abas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboCidade;
    private javax.swing.JComboBox<String> jComboEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelCidade1;
    private javax.swing.JLabel jLabelData1;
    private javax.swing.JLabel jLabelData2;
    private javax.swing.JLabel jLabelData3;
    private javax.swing.JLabel jLabelData4;
    private javax.swing.JLabel jLabelData5;
    private javax.swing.JLabel jLabelData6;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelEstado1;
    private javax.swing.JLabel jLabelHora1;
    private javax.swing.JLabel jLabelHora2;
    private javax.swing.JLabel jLabelHora3;
    private javax.swing.JLabel jLabelHora4;
    private javax.swing.JLabel jLabelHora5;
    private javax.swing.JLabel jLabelHora6;
    private javax.swing.JLabel jLabelHora7;
    private javax.swing.JLabel jLabelHora8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTablePrevisao1;
    private javax.swing.JTable jTablePrevisao2;
    private javax.swing.JTable jTablePrevisao3;
    private javax.swing.JTable jTablePrevisao4;
    private javax.swing.JTable jTablePrevisao5;
    private javax.swing.JTable jTablePrevisao6;
    private javax.swing.JTable jTablePrevisao7;
    private javax.swing.JTable jTablePrevisao8;
    // End of variables declaration//GEN-END:variables
}
